<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { adminApi, type AdminProduct } from '@/services/adminApi'

const route = useRoute(); const router = useRouter(); const id = String(route.params.id)
const isNew = computed(() => id === 'nuevo'); const product = ref<AdminProduct | null>(null); const isLoading = ref(true); const isSaving = ref(false); const isDeleting = ref(false); const isDeleteDialogOpen = ref(false); const deleteError = ref(''); const isUploading = ref(false); const message = ref('')
const blank = (): AdminProduct => ({ _id:'', name:'', sku:'', collection:'', categories:[], palette:'', description:'', dimensions:'', image:'', price:0, available:true, featured:false })
const categories = computed(() => product.value?.categories?.join(', ') || '')
function setCategories(value:string) { if (product.value) product.value.categories = value.split(',').map((item) => item.trim()).filter(Boolean) }
async function load() { if (isNew.value) { product.value = blank(); isLoading.value = false; return }; try { product.value = (await adminApi.products()).data.find((item) => item._id === id) || null; if (!product.value) message.value = 'Producto no encontrado.' } catch (reason:any) { message.value = reason.message || 'No pudimos cargar el producto.' } finally { isLoading.value = false } }
async function upload(event:Event) { const input=event.target as HTMLInputElement; const file=input.files?.[0]; input.value=''; if (!file || !product.value) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 10 * 1024 * 1024) { message.value='Usa una imagen JPG, PNG o WEBP de máximo 10 MB.'; return }; isUploading.value=true; try { const image=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject();reader.readAsDataURL(file)}); product.value.image=(await adminApi.uploadProductImage(image)).data.url; message.value='Imagen cargada. Guarda los cambios para publicarla.' } catch (reason:any) { message.value=reason.message || 'No pudimos cargar la imagen.' } finally { isUploading.value=false } }
async function save() { if (!product.value) return; isSaving.value=true; message.value=''; try { const { _id,...payload }=product.value; const status=isNew.value ? 'created' : 'updated'; await (isNew.value ? adminApi.createProduct(payload) : adminApi.updateProduct(_id,payload)); await router.replace({ path: '/admin/productos', query: { status } }) } catch(reason:any) { message.value=reason.message || 'No pudimos guardar el producto.' } finally { isSaving.value=false } }
function openDeleteDialog() { deleteError.value=''; isDeleteDialogOpen.value=true }
async function remove() { if (!product.value) return; isDeleting.value=true; deleteError.value=''; try { await adminApi.deleteProduct(product.value._id); await router.replace({ path: '/admin/productos', query: { status: 'deleted' } }) } catch(reason:any) { deleteError.value=reason.message || 'No pudimos eliminar el producto.' } finally { isDeleting.value=false } }
onMounted(load)
</script>

<template><main class="editor-page"><header><RouterLink to="/admin/productos">← Volver al catálogo</RouterLink></header><p v-if="isLoading" class="status">Cargando producto...</p><section v-else-if="product" class="editor"><div><p class="eyebrow">{{ isNew ? 'Nuevo producto' : 'Editar producto' }}</p><h1>{{ product.name || 'Sin nombre' }}</h1></div><form @submit.prevent="save"><div class="image"><img v-if="product.image" :src="product.image" :alt="product.name"><div v-else>Sin imagen</div><label>{{ isUploading ? 'Cargando...' : product.image ? 'Cambiar imagen' : 'Agregar imagen' }}<input :disabled="isUploading" accept="image/jpeg,image/png,image/webp" type="file" @change="upload"></label><small>Opcional. JPG, PNG o WEBP. Máximo 10 MB.</small></div><div class="fields"><label>Nombre<input v-model.trim="product.name" required></label><label>SKU<input v-model.trim="product.sku" required></label><label>Colección<input v-model.trim="product.collection" required></label><label>Paleta<input v-model.trim="product.palette" required></label><label>Medidas<input v-model.trim="product.dimensions" required></label><label>Precio USD<input v-model.number="product.price" required min="0" step="0.01" type="number"></label><label class="wide">Categorías<input :value="categories" @input="setCategories(($event.target as HTMLInputElement).value)"></label><label class="wide">Descripción<textarea v-model.trim="product.description" required rows="5"></textarea></label></div><div class="toggles"><label><input v-model="product.available" type="checkbox"> Disponible</label><label><input v-model="product.featured" type="checkbox"> Destacado</label></div><p v-if="message" class="status">{{ message }}</p><div class="actions"><button :disabled="isSaving || isDeleting || isUploading" type="submit">{{ isSaving ? 'Guardando...' : 'Guardar cambios' }}</button><button v-if="!isNew" :disabled="isSaving || isDeleting || isUploading" class="delete-btn" type="button" @click="openDeleteDialog">Eliminar producto</button></div></form></section><p v-else class="status">{{ message }}</p><Teleport to="body"><div v-if="isDeleteDialogOpen" class="modal-backdrop" @click.self="isDeleteDialogOpen=false"><section class="delete-modal" aria-modal="true" role="dialog" aria-labelledby="delete-title"><p class="eyebrow">Eliminar producto</p><h2 id="delete-title">¿Eliminar {{ product?.name }}?</h2><p>Dejará de aparecer en el catálogo y no estará disponible para comprar.</p><p v-if="deleteError" class="delete-error">{{ deleteError }}</p><div><button :disabled="isDeleting" class="cancel-btn" type="button" @click="isDeleteDialogOpen=false">Cancelar</button><button :disabled="isDeleting" class="delete-btn" type="button" @click="remove">{{ isDeleting ? 'Eliminando...' : 'Sí, eliminar' }}</button></div></section></div></Teleport></main></template>

<style lang="scss" scoped>.editor-page{min-height:100vh;padding:28px 5vw 80px;color:#211817;background:#fffaf6;font-family:$font-principal}header a{color:#9a4f58;font:600 11px $font-principal;text-decoration:none}.editor{max-width:800px;margin:62px auto 0}.eyebrow{margin:0;color:#9a4f58;font-size:10px;letter-spacing:1.4px;text-transform:uppercase}.editor h1{margin:10px 0 28px;font:500 clamp(38px,6vw,64px)/.9 $font-secondary;letter-spacing:-.06em}form{padding:24px;background:#faf5f1;border:1px solid #e4d7d0;border-radius:9px}.image{display:flex;align-items:center;gap:15px;padding-bottom:20px}.image img,.image>div{width:100px;height:100px;object-fit:cover;border-radius:5px}.image>div{display:grid;place-items:center;background:#eee4de;color:#9c8c86;font-size:11px}.image label,button{border:0;border-radius:4px;padding:12px 16px;color:#fffaf6;background:#9a4f58;font:600 10px $font-principal;letter-spacing:.05em;text-transform:uppercase;cursor:pointer}.image label{position:relative}.image label input{position:absolute;inset:0;width:100%;height:100%;opacity:0}.image small{color:#706663;font-size:10px}.fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.fields label,.toggles label{display:flex;flex-direction:column;gap:5px;color:#706663;font:600 10px $font-principal;letter-spacing:.05em;text-transform:uppercase}.fields .wide{grid-column:1/-1}input,textarea{box-sizing:border-box;width:100%;border:1px solid #d9c8c0;border-radius:4px;padding:11px;color:#211817;background:#fffdfb;font:14px $font-principal}textarea{resize:vertical}.toggles{display:flex;gap:16px;margin:18px 0}.toggles label{flex-direction:row;align-items:center}.toggles input{width:auto}.status{margin:18px 0;color:#706663;font-size:13px}.actions{display:flex;flex-wrap:wrap;gap:10px}.delete-btn{background:#7a3338}.modal-backdrop{position:fixed;z-index:20;inset:0;display:grid;place-items:center;padding:20px;background:rgba(33,24,23,.5)}.delete-modal{width:min(100%,420px);box-sizing:border-box;padding:30px;background:#fffaf6;border:1px solid #e4d7d0;border-radius:10px;box-shadow:0 20px 60px rgba(33,24,23,.25)}.delete-modal h2{margin:10px 0 12px;font:500 35px/.9 $font-secondary;letter-spacing:-.05em}.delete-modal>p:not(.eyebrow):not(.delete-error){margin:0;color:#706663;font-size:14px;line-height:1.5}.delete-modal>div{display:flex;justify-content:flex-end;gap:10px;margin-top:24px}.cancel-btn{color:#706663;background:transparent;border:1px solid #d9c8c0}.delete-error{margin:14px 0 0;color:#9a4f58;font-size:13px}@media(max-width:640px){.editor{margin-top:42px}.image{align-items:flex-start;flex-wrap:wrap}.fields{grid-template-columns:1fr}.fields .wide{grid-column:auto}.delete-modal{padding:24px}.delete-modal>div{flex-direction:column-reverse}.delete-modal button{width:100%}}</style>
